#include <Eigen/Dense>
#include <gtest/gtest.h>
#include <rclcpp/rclcpp.hpp>
#include <rclcpp/wait_for_message.hpp>
#include <geometry_msgs/msg/wrench_stamped.hpp>
#include <geometry_msgs/msg/pose_stamped.hpp>
#include <std_msgs/msg/float64_multi_array.hpp>

// Controller node name as set in the controller manager configuration.
// Adjust to match your deployment if it differs.
const std::string ctrl_name = "CartesianImpedance_trajectory_controller";

// Node shared across all tests in this translation unit.
rclcpp::Node::SharedPtr test_node;

// Wait until the controller's publisher is discovered by the local DDS participant.
// Without this, wait_for_message may time out before DDS discovery completes.
static void wait_for_publisher(
  const std::string & topic,
  std::chrono::seconds timeout = std::chrono::seconds(15))
{
  auto deadline = std::chrono::steady_clock::now() + timeout;
  while (test_node->count_publishers(topic) == 0) {
    rclcpp::spin_some(test_node);
    rclcpp::sleep_for(std::chrono::milliseconds(200));
    if (std::chrono::steady_clock::now() > deadline) { break; }
  }
}

// ROSBaseTests verify that key topics published by the library are being written.

TEST(ROSBaseTests, commandedtorqueTests)
{
  const std::string torque_topic{"/" + ctrl_name + "/commanded_torques"};
  wait_for_publisher(torque_topic);
  for (int i = 0; i < 5; i++) {
    std_msgs::msg::Float64MultiArray msg;
    bool received =
        rclcpp::wait_for_message(msg, test_node, torque_topic, std::chrono::seconds(5));

    ASSERT_TRUE(received) << "Did not receive message on iteration " << i + 1;
    ASSERT_FALSE(msg.data.empty()) << "Commanded torques message has no data";
    EXPECT_LE(std::abs(msg.data[0]), 1000.0);
  }
}

// ROSParameterTests verify that the controller exposes all expected ROS 2 parameters.
// In ROS 2 the dynamic_reconfigure sub-namespaces are replaced by flat dotted parameter names
// generated by generate_parameter_library (e.g. "wrench.force_x" instead of
// "cartesian_wrench_reconfigure/f_x").
TEST(ROSParameterTests, paramTest)
{
  auto param_client = std::make_shared<rclcpp::SyncParametersClient>(test_node, ctrl_name);
  ASSERT_TRUE(param_client->wait_for_service(std::chrono::seconds(10)))
      << "Parameter service of controller node [" << ctrl_name << "] is not available.";

  const std::vector<std::string> params_to_check = {
    "wrench.apply_wrench",
    "wrench.force_x",
    "wrench.force_y",
    "wrench.force_z",
    "wrench.torque_x",
    "wrench.torque_y",
    "wrench.torque_z",
    "damping.nullspace_damping",
    "damping.rotation.x",
    "damping.rotation.y",
    "damping.rotation.z",
    "damping.translation.x",
    "damping.translation.y",
    "damping.translation.z",
    "damping.update_damping_factors",
    "delta_tau_max",
    "end_effector",
    "filtering.nullspace_config",
    "filtering.pose",
    "filtering.stiffness",
    "filtering.wrench",
    "joints",
    "stiffness.nullspace_stiffness",
    "stiffness.rotation.x",
    "stiffness.rotation.y",
    "stiffness.rotation.z",
    "stiffness.translation.x",
    "stiffness.translation.y",
    "stiffness.translation.z",
    "stiffness.update_stiffness",
    "update_frequency",
    "verbosity.state_msgs",
    "verbosity.tf_frames",
    "verbosity.verbose_print",
    "wrench_ee_frame",
  };

  for (const auto & param : params_to_check) {
    EXPECT_TRUE(param_client->has_parameter(param))
        << "Parameter [" << param << "] does NOT exist on node [" << ctrl_name << "].";
  }
}

// ROSReconfigureTests verify that runtime parameter changes (formerly dynamic_reconfigure)
// are accepted by the controller.  Each test sets a parameter via the ROS 2 parameter
// service and reads it back to confirm the new value was applied.
TEST(ROSReconfigureTests, wrenchTest)
{
  auto param_client = std::make_shared<rclcpp::SyncParametersClient>(test_node, ctrl_name);
  ASSERT_TRUE(param_client->wait_for_service(std::chrono::seconds(10)));

  auto results = param_client->set_parameters({rclcpp::Parameter("wrench.force_x", 5.0)});
  ASSERT_EQ(results.size(), 1u);
  EXPECT_TRUE(results[0].successful) << results[0].reason;

  auto params = param_client->get_parameters({"wrench.force_x"});
  ASSERT_EQ(params.size(), 1u);
  EXPECT_DOUBLE_EQ(params[0].as_double(), 5.0);

  // Reset to zero so subsequent tests start from a clean state
  param_client->set_parameters({rclcpp::Parameter("wrench.force_x", 0.0)});
}

TEST(ROSReconfigureTests, stiffnessTest)
{
  auto param_client = std::make_shared<rclcpp::SyncParametersClient>(test_node, ctrl_name);
  ASSERT_TRUE(param_client->wait_for_service(std::chrono::seconds(5)));

  auto results =
      param_client->set_parameters({rclcpp::Parameter("stiffness.translation.x", 100.0)});
  ASSERT_EQ(results.size(), 1u);
  EXPECT_TRUE(results[0].successful) << results[0].reason;

  auto params = param_client->get_parameters({"stiffness.translation.x"});
  ASSERT_EQ(params.size(), 1u);
  EXPECT_DOUBLE_EQ(params[0].as_double(), 100.0);
}

TEST(ROSReconfigureTests, dampingTest)
{
  auto param_client = std::make_shared<rclcpp::SyncParametersClient>(test_node, ctrl_name);
  ASSERT_TRUE(param_client->wait_for_service(std::chrono::seconds(5)));

  auto results =
      param_client->set_parameters({rclcpp::Parameter("damping.translation.x", 0.75)});
  ASSERT_EQ(results.size(), 1u);
  EXPECT_TRUE(results[0].successful) << results[0].reason;

  auto params = param_client->get_parameters({"damping.translation.x"});
  ASSERT_EQ(params.size(), 1u);
  EXPECT_DOUBLE_EQ(params[0].as_double(), 0.75);
}

int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);
  test_node = rclcpp::Node::make_shared("test_ros_node");
  testing::InitGoogleTest(&argc, argv);
  const int result = RUN_ALL_TESTS();
  test_node.reset();  // destroy node before shutdown to avoid use-after-free on DDS context
  rclcpp::shutdown();
  return result;
}
